window.vocabulary = {
    "Day 08": [
        { word: "planet", meaning: "행성" },
        { word: "daytime", meaning: "낮" },
        { word: "revolution", meaning: "혁명, 공전" },
        { word: "passage", meaning: "통로, 구절" },
        { word: "economy", meaning: "경제" },
        { word: "repeatedly", meaning: "반복해서" },
        { word: "convenient", meaning: "편리한" },
        { word: "audience", meaning: "청중" },
        { word: "climate", meaning: "기후" },
        { word: "typical", meaning: "전형적인" },
        { word: "experiment", meaning: "실험" },
        { word: "effort", meaning: "노력" },
        { word: "compose", meaning: "작곡하다, 구성하다" },
        { word: "quit", meaning: "그만두다" },
        { word: "hesitate", meaning: "망설이다" },
        { word: "rescue", meaning: "구조하다" },
        { word: "cure", meaning: "치료하다" },
        { word: "vehicle", meaning: "탈것, 차량" },
        { word: "in order to", meaning: "~하기 위해" },
        { word: "by chance", meaning: "우연히" }
    ],
    "Day 09": [
        { word: "clue", meaning: "단서" },
        { word: "unhealthy", meaning: "건강하지 않은" },
        { word: "generous", meaning: "관대한" },
        { word: "confuse", meaning: "혼란스럽게 하다" },
        { word: "genuine", meaning: "진짜의" },
        { word: "participate", meaning: "참여하다" },
        { word: "strict", meaning: "엄격한" },
        { word: "drag", meaning: "끌다" },
        { word: "glory", meaning: "영광" },
        { word: "invitation", meaning: "초대" },
        { word: "difference", meaning: "차이" },
        { word: "measure", meaning: "재다, 측정하다" },
        { word: "awake", meaning: "깨어있는" },
        { word: "object", meaning: "물건, 반대하다" },
        { word: "respect", meaning: "존경하다" },
        { word: "document", meaning: "문서" },
        { word: "spine", meaning: "척추" },
        { word: "addicted", meaning: "중독된" },
        { word: "talk behind one's back", meaning: "뒷담화하다" },
        { word: "make it", meaning: "해내다, 성공하다" }
    ]
};
