window.vocabulary = {
    "Day 08": [
        { word: "planet", meaning: "행성" },
        { word: "daytime", meaning: "낮" },
        { word: "revolution", meaning: "혁명, 공전" },
        { word: "passage", meaning: "통로, 구절" },
        { word: "economy", meaning: "경제" },
        { word: "repeatedly", meaning: "반복해서" },
        { word: "convenient", meaning: "편리한" },
        { word: "audience", meaning: "청중" },
        { word: "climate", meaning: "기후" },
        { word: "typical", meaning: "전형적인" },
        { word: "experiment", meaning: "실험" },
        { word: "effort", meaning: "노력" },
        { word: "compose", meaning: "작곡하다, 구성하다" },
        { word: "quit", meaning: "그만두다" },
        { word: "hesitate", meaning: "망설이다" },
        { word: "rescue", meaning: "구조하다" },
        { word: "cure", meaning: "치료하다" },
        { word: "vehicle", meaning: "탈것, 차량" },
        { word: "in order to", meaning: "~하기 위해" },
        { word: "by chance", meaning: "우연히" }
    ],
    "Day 09": [
        { word: "clue", meaning: "단서" },
        { word: "unhealthy", meaning: "건강하지 않은" },
        { word: "generous", meaning: "관대한" },
        { word: "confuse", meaning: "혼란스럽게 하다" },
        { word: "genuine", meaning: "진짜의" },
        { word: "participate", meaning: "참여하다" },
        { word: "strict", meaning: "엄격한" },
        { word: "drag", meaning: "끌다" },
        { word: "glory", meaning: "영광" },
        { word: "invitation", meaning: "초대" },
        { word: "difference", meaning: "차이" },
        { word: "measure", meaning: "재다, 측정하다" },
        { word: "awake", meaning: "깨어있는" },
        { word: "object", meaning: "물건, 반대하다" },
        { word: "respect", meaning: "존경하다" },
        { word: "document", meaning: "문서" },
        { word: "spine", meaning: "척추" },
        { word: "addicted", meaning: "중독된" },
        { word: "talk behind one's back", meaning: "뒷담화하다" },
        { word: "make it", meaning: "해내다, 성공하다" }
    ]
};

/* Day 10-14 Update */
vocabulary["Day 10"] = [
    { word: "thankful", meaning: "감사하는" },
    { word: "benefit", meaning: "혜택, 이익" },
    { word: "communicate", meaning: "의사소통하다" },
    { word: "impossible", meaning: "불가능한" },
    { word: "effect", meaning: "효과, 영향" },
    { word: "edit", meaning: "편집하다" },
    { word: "foreign", meaning: "외국의" },
    { word: "totally", meaning: "완전히" },
    { word: "parade", meaning: "행진, 퍼레이드" },
    { word: "increase", meaning: "증가하다" },
    { word: "pleasure", meaning: "기쁨" },
    { word: "notice", meaning: "알아차리다, 공지" },
    { word: "annoy", meaning: "짜증나게 하다" },
    { word: "colleague", meaning: "동료" },
    { word: "option", meaning: "선택" },
    { word: "complain", meaning: "불평하다" },
    { word: "garage", meaning: "차고" },
    { word: "lay", meaning: "놓다, 눕히다" },
    { word: "carry out", meaning: "수행하다" },
    { word: "be based on", meaning: "~에 근거하다" }
];

vocabulary["Day 11"] = [
    { word: "available", meaning: "이용 가능한" },
    { word: "treat", meaning: "다루다, 대접하다" },
    { word: "education", meaning: "교육" },
    { word: "community", meaning: "지역사회, 공동체" },
    { word: "sweat", meaning: "땀, 땀을 흘리다" },
    { word: "perform", meaning: "공연하다, 수행하다" },
    { word: "anxious", meaning: "불안해하는" },
    { word: "select", meaning: "선택하다" },
    { word: "successful", meaning: "성공적인" },
    { word: "military", meaning: "군대의" },
    { word: "opportunity", meaning: "기회" },
    { word: "staff", meaning: "직원" },
    { word: "prefer", meaning: "선호하다" },
    { word: "index", meaning: "색인, 지수" },
    { word: "appearance", meaning: "외모, 출현" },
    { word: "swear", meaning: "맹세하다, 욕하다" },
    { word: "deny", meaning: "부인하다" },
    { word: "confirm", meaning: "확인하다" },
    { word: "from now on", meaning: "지금부터" },
    { word: "move on", meaning: "넘어가다, 이동하다" }
];

vocabulary["Day 12"] = [
    { word: "belief", meaning: "믿음" },
    { word: "abroad", meaning: "해외로" },
    { word: "kindness", meaning: "친절" },
    { word: "talented", meaning: "재능 있는" },
    { word: "offer", meaning: "주다, 제안하다" },
    { word: "forgive", meaning: "용서하다" },
    { word: "manner", meaning: "태도, 예의" },
    { word: "crowd", meaning: "군중" },
    { word: "companion", meaning: "동료, 친구" },
    { word: "reduce", meaning: "줄이다" },
    { word: "normally", meaning: "보통, 대개" },
    { word: "acquire", meaning: "얻다, 습득하다" },
    { word: "addition", meaning: "추가, 덧셈" },
    { word: "excitement", meaning: "흥분" },
    { word: "neither", meaning: "어느 쪽도 ~아닌" },
    { word: "fortune", meaning: "운, 재산" },
    { word: "swallow", meaning: "삼키다, 제비" },
    { word: "nowadays", meaning: "요즘" },
    { word: "far from", meaning: "~와 거리가 먼" },
    { word: "look up", meaning: "찾아보다, 올려다보다" }
];

vocabulary["Day 13"] = [
    { word: "context", meaning: "문맥, 상황" },
    { word: "beginning", meaning: "시작" },
    { word: "growth", meaning: "성장" },
    { word: "per", meaning: "~당, ~마다" },
    { word: "recover", meaning: "회복하다" },
    { word: "economic", meaning: "경제의" },
    { word: "overcome", meaning: "극복하다" },
    { word: "manage", meaning: "관리하다, 해내다" },
    { word: "graduate", meaning: "졸업하다" },
    { word: "charm", meaning: "매력" },
    { word: "truly", meaning: "진심으로, 정말로" },
    { word: "avoid", meaning: "피하다" },
    { word: "admit", meaning: "인정하다" },
    { word: "smooth", meaning: "부드러운" },
    { word: "surface", meaning: "표면" },
    { word: "negative", meaning: "부정적인" },
    { word: "status", meaning: "지위, 상태" },
    { word: "system", meaning: "시스템, 체계" },
    { word: "sign up for", meaning: "~에 등록하다" },
    { word: "along with", meaning: "~와 함께" }
];

vocabulary["Day 14"] = [
    { word: "positive", meaning: "긍정적인" },
    { word: "neighborhood", meaning: "이웃, 동네" },
    { word: "express", meaning: "표현하다" },
    { word: "achieve", meaning: "성취하다" },
    { word: "instrument", meaning: "도구, 악기" },
    { word: "ensure", meaning: "보장하다" },
    { word: "competition", meaning: "경쟁" },
    { word: "repair", meaning: "수리하다" },
    { word: "enjoyable", meaning: "즐거운" },
    { word: "crush", meaning: "으스러뜨리다" },
    { word: "ability", meaning: "능력" },
    { word: "imagine", meaning: "상상하다" },
    { word: "performance", meaning: "공연, 실적" },
    { word: "aid", meaning: "도움, 원조" },
    { word: "facility", meaning: "시설" },
    { word: "access", meaning: "접근" },
    { word: "conversation", meaning: "대화" },
    { word: "invent", meaning: "발명하다" },
    { word: "a number of", meaning: "많은" },
    { word: "check out", meaning: "확인하다, 대출하다" }
];

vocabulary["Day 15"] = [
    { word: 'shoot', meaning: '쏘다/촬영하다' },
    { word: 'organization', meaning: '조직/단체' },
    { word: 'rush', meaning: '서두르다/돌진' },
    { word: 'peaceful', meaning: '평화로운' },
    { word: 'occur', meaning: '일어나다/발생하다' },
    { word: 'advance', meaning: '나아가다/전진' },
    { word: 'sensitive', meaning: '민감한/예민한' },
    { word: 'reply', meaning: '대답하다/답장' },
    { word: 'attitude', meaning: '태도/자세' },
    { word: 'illegal', meaning: '불법의' },
    { word: 'visual', meaning: '시각의/눈에 보이는' },
    { word: 'mood', meaning: '기분/분위기' },
    { word: 'firm', meaning: '단단한/확고한/회사' },
    { word: 'unfortunately', meaning: '불행하게도/유감스럽게도' },
    { word: 'genius', meaning: '천재' },
    { word: 'reasonable', meaning: '합리적인/타당한' },
    { word: 'horror', meaning: '공포' },
    { word: 'abandon', meaning: '버리다/포기하다' },
    { word: 'come to an end', meaning: '끝나다' },
    { word: 'look forward to', meaning: '~을 고대하다(기대하다)' }
];

vocabulary["Day 16"] = [
    { word: 'announce', meaning: '발표하다/알리다' },
    { word: 'saying', meaning: '속담/격언' },
    { word: 'silence', meaning: '침묵/고요' },
    { word: 'elect', meaning: '선출하다/뽑다' },
    { word: 'professor', meaning: '교수' },
    { word: 'lastly', meaning: '마지막으로' },
    { word: 'panic', meaning: '공포/당황' },
    { word: 'guarantee', meaning: '보장하다/보증' },
    { word: 'calculate', meaning: '계산하다' },
    { word: 'glow', meaning: '빛나다/타오르다' },
    { word: 'research', meaning: '연구하다/조사하다' },
    { word: 'summarize', meaning: '요약하다' },
    { word: 'detective', meaning: '탐정/형사' },
    { word: 'charity', meaning: '자선/자선단체' },
    { word: 'mission', meaning: '임무/사명' },
    { word: 'former', meaning: '이전의/전임의' },
    { word: 'scientific', meaning: '과학의/과학적인' },
    { word: 'instant', meaning: '즉각적인/인스턴트의' },
    { word: 'B as well as A', meaning: 'A뿐만 아니라 B도' },
    { word: 'little by little', meaning: '조금씩/점차' }
];

vocabulary["Day 17"] = [
    { word: 'educate', meaning: '교육하다' },
    { word: 'attractive', meaning: '매력적인' },
    { word: 'sparkle', meaning: '반짝이다' },
    { word: 'influence', meaning: '영향을 주다/영향' },
    { word: 'standard', meaning: '기준/표준' },
    { word: 'myth', meaning: '신화/통념' },
    { word: 'shave', meaning: '면도하다' },
    { word: 'survive', meaning: '살아남다/생존하다' },
    { word: 'lightning', meaning: '번개' },
    { word: 'threat', meaning: '위협/협박' },
    { word: 'arrange', meaning: '배열하다/정리하다/마련하다' },
    { word: 'insist', meaning: '고집하다/주장하다' },
    { word: 'complaint', meaning: '불평/항의' },
    { word: 'ancient', meaning: '고대의' },
    { word: 'moreover', meaning: '게다가/더욱이' },
    { word: 'quarrel', meaning: '말다툼하다/싸우다' },
    { word: 'remove', meaning: '제거하다/치우다' },
    { word: 'thirst', meaning: '갈증/목마름' },
    { word: 'allow A to V', meaning: 'A가 ~하게 허락하다' },
    { word: 'break out', meaning: '발생하다/일어나다' }
];

vocabulary["Day 18"] = [
    { word: 'attract', meaning: '마음을 끌다/유인하다' },
    { word: 'disappointed', meaning: '실망한' },
    { word: 'mess', meaning: '엉망진창/혼란' },
    { word: 'likely', meaning: '~할 것 같은' },
    { word: 'postpone', meaning: '연기하다/미루다' },
    { word: 'innocent', meaning: '무죄의/순수한' },
    { word: 'apology', meaning: '사과' },
    { word: 'mostly', meaning: '대개/주로' },
    { word: 'fortunate', meaning: '운 좋은/다행한' },
    { word: 'retire', meaning: '은퇴하다/퇴직하다' },
    { word: 'counselor', meaning: '상담가/카운슬러' },
    { word: 'generation', meaning: '세대' },
    { word: 'persuade', meaning: '설득하다' },
    { word: 'competitive', meaning: '경쟁적인/경쟁력 있는' },
    { word: 'risk', meaning: '위험/감행하다' },
    { word: 'pale', meaning: '창백한/옅은' },
    { word: 'consist', meaning: '구성되다/이루어져 있다' },
    { word: 'disappear', meaning: '사라지다' },
    { word: 'from time to time', meaning: '가끔/때때로' },
    { word: 'keep in mind', meaning: '명심하다' }
];
